[[HarfBuzz_ICU]]
arch = "aarch64"
git-tree-sha1 = "c6101d5f0bb50d9f33815dd98519b5a0d1c5f0e5"
os = "macos"

    [[HarfBuzz_ICU.download]]
    sha256 = "9d6d565f89fac7abedf533194495ae10e299f0ccb840fb519527fa3a5cff0006"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.aarch64-apple-darwin.tar.gz"
[[HarfBuzz_ICU]]
arch = "aarch64"
git-tree-sha1 = "a3e8429549cf78715c798fc37b8e5eb9889d33ae"
libc = "glibc"
os = "linux"

    [[HarfBuzz_ICU.download]]
    sha256 = "5caee1baa6a31b701e8469c3d6f448c09edf43d95ff35068a3d26a9273ca33ab"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.aarch64-linux-gnu.tar.gz"
[[HarfBuzz_ICU]]
arch = "aarch64"
git-tree-sha1 = "41a62c6f399c2518af766604d13314dbb16b783f"
libc = "musl"
os = "linux"

    [[HarfBuzz_ICU.download]]
    sha256 = "00a75402ea3504f488ca61c019dceb005b0192cf1f02cf80cff65f2136889491"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.aarch64-linux-musl.tar.gz"
[[HarfBuzz_ICU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fc0050a433c601051bd60b0c6a88b32806ac0a6c"
libc = "glibc"
os = "linux"

    [[HarfBuzz_ICU.download]]
    sha256 = "f91abd94d2c1ef4d1c03cb60190951c5f52cc8db8428cd4992cb964fe6d36e06"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.armv6l-linux-gnueabihf.tar.gz"
[[HarfBuzz_ICU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c6e2efba35300812a7b6f156cf7b9d15e8a33f14"
libc = "musl"
os = "linux"

    [[HarfBuzz_ICU.download]]
    sha256 = "539312db07cd3d7a074602e759f0ed3cbf78ab6fdc4f85ca94a5427cd54ec31d"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.armv6l-linux-musleabihf.tar.gz"
[[HarfBuzz_ICU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "285c9fc0ee3832c39cc1acc0d67adff39603de61"
libc = "glibc"
os = "linux"

    [[HarfBuzz_ICU.download]]
    sha256 = "bb4a7ff59c3a16924d6f793acdabc33e75100f806c6a10aa2065522c0562e16e"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.armv7l-linux-gnueabihf.tar.gz"
[[HarfBuzz_ICU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "22d049245daf2d4dfb1f943341b6b89263a62c88"
libc = "musl"
os = "linux"

    [[HarfBuzz_ICU.download]]
    sha256 = "5acb2f294b37b5565293eafab22874acfea5d68d6cc9c95c43b397f3e97bf244"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.armv7l-linux-musleabihf.tar.gz"
[[HarfBuzz_ICU]]
arch = "i686"
git-tree-sha1 = "6760cde5940dd0106035e5cec0696ad08bb67c2f"
libc = "glibc"
os = "linux"

    [[HarfBuzz_ICU.download]]
    sha256 = "16cf4868bf8c4b2bd32a5d732a7e4bcb9881a8c6b0c086c7e571f986f4782acd"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.i686-linux-gnu.tar.gz"
[[HarfBuzz_ICU]]
arch = "i686"
git-tree-sha1 = "e39a354dd336ba91fefbf47187302c384ea5fdcb"
libc = "musl"
os = "linux"

    [[HarfBuzz_ICU.download]]
    sha256 = "ae0cb7492a8bccea0a04427d25361cb640b9424be0c4a8d5c5cb6f4226451c65"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.i686-linux-musl.tar.gz"
[[HarfBuzz_ICU]]
arch = "i686"
git-tree-sha1 = "5f8f1df4e9e40776f1880f13a9820d61adf4e5fa"
os = "windows"

    [[HarfBuzz_ICU.download]]
    sha256 = "d4d4adfa08c54f968039df5f32a8b49f1094c981f56a5ec74896d291d7346e64"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.i686-w64-mingw32.tar.gz"
[[HarfBuzz_ICU]]
arch = "powerpc64le"
git-tree-sha1 = "c882531795237ebebb1420962675934ec023a744"
libc = "glibc"
os = "linux"

    [[HarfBuzz_ICU.download]]
    sha256 = "3d563e02ee179a4c5461f7fc7451c0b1ee37be73b343e5c9f3ff252c14515def"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.powerpc64le-linux-gnu.tar.gz"
[[HarfBuzz_ICU]]
arch = "x86_64"
git-tree-sha1 = "fa0aaf47985dbcf32131c98661b61b32ee74ac5a"
os = "macos"

    [[HarfBuzz_ICU.download]]
    sha256 = "a74126e046b8a3aecf8f508e395b4eaa9f89da195477d2744a7f352474a16302"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.x86_64-apple-darwin.tar.gz"
[[HarfBuzz_ICU]]
arch = "x86_64"
git-tree-sha1 = "34b9d05047e98debd6ea904c3b0df7dd2dfe2f8a"
libc = "glibc"
os = "linux"

    [[HarfBuzz_ICU.download]]
    sha256 = "ad0a8132dba11830556bcc3fab5cb305ed01f9b03d3b43e9c39d25e57e25e878"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.x86_64-linux-gnu.tar.gz"
[[HarfBuzz_ICU]]
arch = "x86_64"
git-tree-sha1 = "d56ec9adb405e5295dd15c6810cbd11d8dd85a15"
libc = "musl"
os = "linux"

    [[HarfBuzz_ICU.download]]
    sha256 = "4d9e68b8f91cbd71133701f2fb700ebfef5a5b2a131f618b1be856db47212f22"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.x86_64-linux-musl.tar.gz"
[[HarfBuzz_ICU]]
arch = "x86_64"
git-tree-sha1 = "65a31bd71cfab524d8e35263ff7884607020aed2"
os = "freebsd"

    [[HarfBuzz_ICU.download]]
    sha256 = "8b4c8fe4d754398f0a431d6dda291494d170736387b548c9b66adb0ebdae8c92"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.x86_64-unknown-freebsd.tar.gz"
[[HarfBuzz_ICU]]
arch = "x86_64"
git-tree-sha1 = "6c7c63ee9be6d6e51286efa77702c1392f328572"
os = "windows"

    [[HarfBuzz_ICU.download]]
    sha256 = "893f704203a47ad3f01f06143f41afb5d0e453eff30609e66d52ca1d0675af71"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_ICU_jll.jl/releases/download/HarfBuzz_ICU-v8.5.0+0/HarfBuzz_ICU.v8.5.0.x86_64-w64-mingw32.tar.gz"
